# Generated by Django 5.1.4 on 2024-12-10 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('category', models.CharField(choices=[('FRONTEND', 'Front-end'), ('BACKEND', 'Back-end'), ('LANGUAGE', 'Langage'), ('DATA', 'Data Science'), ('TOOLS', 'Outils')], max_length=50, verbose_name='Catégorie')),
                ('icon', models.ImageField(upload_to='tech_icons/', verbose_name='Icône')),
            ],
            options={
                'verbose_name': 'Technologie',
                'verbose_name_plural': 'Technologies',
            },
        ),
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='URL LinkedIn')),
                ('badge_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('tech_stack', models.ManyToManyField(to='badges.techstack', verbose_name='Technologies')),
            ],
            options={
                'verbose_name': 'Profil développeur',
                'verbose_name_plural': 'Profils développeurs',
            },
        ),
    ]
