# Generated by Django 5.1.4 on 2024-12-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developerprofile',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='URL GitHub'),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Titre du poste'),
        ),
    ]
