# Generated by Django 5.1.4 on 2024-12-10 11:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_developerprofile_github_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='developerprofile',
            name='badge_style',
            field=models.CharField(choices=[('classic', 'Classique'), ('modern', 'Moderne'), ('compact', 'Compact')], default='modern', max_length=20),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='badge_theme',
            field=models.CharField(choices=[('dark', 'Thème sombre'), ('light', 'Thème clair'), ('gradient', 'Dégradé'), ('minimal', 'Minimaliste')], default='dark', max_length=20),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='badge_uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='tech_stack',
            field=models.ManyToManyField(to='badges.techstack'),
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
