# Generated by Django 5.1.4 on 2024-12-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_developerprofile_badge_style_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developerprofile',
            options={},
        ),
        migrations.AlterModelOptions(
            name='techstack',
            options={'ordering': ['category', 'order', 'name']},
        ),
        migrations.RemoveField(
            model_name='developerprofile',
            name='badge_style',
        ),
        migrations.RemoveField(
            model_name='developerprofile',
            name='badge_theme',
        ),
        migrations.AddField(
            model_name='developerprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='techstack',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Image de profil (format carré recommandé)', upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='category',
            field=models.CharField(choices=[('FRONTEND', 'Front-end'), ('BACKEND', 'Back-end'), ('LANGUAGE', 'Langage'), ('DATA', 'Data Science'), ('TOOLS', 'Outils')], max_length=50),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='icon',
            field=models.ImageField(upload_to='tech_icons/'),
        ),
        migrations.AlterField(
            model_name='techstack',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
